---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth
  namespace: ai
spec:
  plugin:
    oAuthIntrospection:
      tokenSource:
        header: Authorization
        headerAuthScheme: Bearer
      clientConfig:
        url: 
        headers:
          Authorization: 
      tokenTypeHint: access_token
      forwardHeaders:
        username: preferred_username
        groups: groups
      identity: preferred_username
