---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bedrock-parent
  namespace: ai
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bapi.${CLUSTERNAME}.${DOMAINNAME}`)
      middlewares:
        - name: jwt
        # - name: oauth
        - name: messagesapi-bedrock
        - name: token-quota-team
        - name: semantic-cache
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bedrock-child-haiku
  namespace: ai
spec:
  parentRefs:
    - name: bedrock-parent
  routes:
    - kind: Rule
      match: Host(`bapi.${CLUSTERNAME}.${DOMAINNAME}`) && PathPrefix(`/anthropic/v1/messages`) && Model(`anthropic.claude-haiku-4-5`)
      services:
        - name: bedrock-svc
          kind: Service
          port: 443
          passHostHeader: false
          middlewares:
            - name: global-token-quota
      middlewares:
        - name: token-quota-user-haiku
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bedrock-child-opus
  namespace: ai
spec:
  parentRefs:
    - name: bedrock-parent
  routes:
    - kind: Rule
      match: Host(`bapi.${CLUSTERNAME}.${DOMAINNAME}`) && PathPrefix(`/anthropic/v1/messages`) && Model(`anthropic.claude-opus-4-7`)
      services:
        - name: bedrock-svc
          kind: Service
          port: 443
          passHostHeader: false
          middlewares:
            - name: global-token-quota
      middlewares:
        - name: token-quota-user-opus

